version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "awscli"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tf8gw52aoubf"
s3_prefix = "awscli"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
